substitutions:
  friendly_name: "Rack Fan"

esphome:
  name: rack-fan

# Throttle writing parameters to the internal flash memory to reduce ESP memory wear / degradation
preferences:
  flash_write_interval: 15min


#########################
# ESP32 AND NETWORK SETUP

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# pid climate log update is noisy, dial it back to warn
logger:
  level: DEBUG
  logs:
    climate: ERROR
    # component includes the custom component, which file the error "Components should block for at most 20-30ms."
    # https://github.com/esphome/issues/issues/4717
    component: ERROR
    # replacement of dht
    htu21d: WARN

# default HA integration, OTA updater and backup http web portal
api:
  # password: !secret device_password
  #encryption:
  #  key: "YOUR_ENCRYPTION_KEY"

ota:
  - platform: esphome
  # password: !secret device_password
  # change to https://esphome.io/components/ota/http_request ?

wifi:
  # Read the wifi/pass from secrets.yaml:
  # wifi_ssid: "My Wifi XX"
  # wifi_password: "XXXXXXX"
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Web server for local diagnostics
web_server:
  port: 80

# https://esphome.io/components/captive_portal.html
#captive_portal:

# needed for sht20
i2c:
  sda: 21
  scl: 22
  scan: true
  frequency: 400kHz

number:

  ## OPTIONAL:
  # RECEIVE KP, KI and KD parameters from input_text.kx helpers in
  # Home Assistant. See the PID controller below
  # These helper values will get saved to flash thus permanently over-riding
  # the initial values set in the PID below.

  # KP
  - platform: template
    name: kp
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.3
    min_value: 0
    max_value: 50
    step: 0.001
    optimistic: true
    set_action:
      lambda: |-
        id(console_thermostat).set_kp( x );

  # KI
  - platform: template
    name: ki
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.0015
    min_value: 0
    max_value: 50
    step: 0.0001
    optimistic: true
    set_action:
      lambda: id(console_thermostat).set_ki( x );

  # KD
  - platform: template
    name: kd
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.0
    min_value: -50
    max_value: 50
    step: 0.001
    optimistic: true
    set_action:
      lambda: id(console_thermostat).set_kd( x );

  # Set threshold low
  - platform: template
    name: "Deadband Threshold Low"
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: -1.0
    min_value: -20
    max_value: 0
    step: 0.1
    optimistic: true
    set_action:
      lambda: id(console_thermostat).set_threshold_low( x );

  # Set threshold high
  - platform: template
    name: "Deadband Threshold High"
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.4
    min_value: 0
    max_value: 20
    step: 0.1
    optimistic: true
    set_action:
      lambda: id(console_thermostat).set_threshold_high( x );

  # Set ki multiplier
  - platform: template
    name: "Deadband ki Multiplier"
    icon: mdi:chart-bell-curve
    restore_value: true
    initial_value: 0.04
    min_value: 0
    max_value: .2
    step: 0.01
    optimistic: true
    set_action:
      lambda: id(console_thermostat).set_ki_multiplier( x );

text_sensor:

  # Send IP Address
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"

  # Send Uptime in raw seconds
  - platform: template
    name: "${friendly_name} Uptime"
    id: uptime_human
    icon: mdi:clock-start

  # Send version of esphome flashed
  - platform: version
    name: "${friendly_name} ESPHome Version"
    icon: mdi:information
    hide_timestamp: true

sensor:

  # Send WiFi signal strength & uptime to HA
  - platform: wifi_signal
    name: "${friendly_name} WiFi Strength"
    update_interval: 60s

  # This is a bit of overkill. It sends a human readable
  # uptime string 1h 41m 32s instead of 6092 seconds
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            # Custom C++ code to generate the result
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  # Read the Tacho PIN and show measured RPM as a sensor (only with 4-pin PWM fans!)
  # See instructions here: https://esphome.io/components/sensor/pulse_counter.html
  - platform: pulse_counter
    pin:
      number: GPIO14 # Connect to any input PIN on the ESP - 4th pin fan1
      # mode: INPUT_PULLUP
      mode:
        input: true
        pullup: true
    unit_of_measurement: 'RPM'
    id: fan_speed
    name: "${friendly_name} Fan Speed 1"
    # default update_interval 60s, missing in the logs otherwise
    update_interval: 5s
    accuracy_decimals: 0
    filters:
      # check the specs, compare with this value
      - multiply: 0.5  # Depending on how many pulses the fan sends per round - should be 0.5 or 1 - try...

  - platform: pulse_counter
    pin:
      number: GPIO26   # Connect to any input PIN on the ESP - 4th pin fan2
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan_speed_2
    name: $friendly_name Fan Speed 2
    accuracy_decimals: 0
    filters:
      - multiply: 0.5  # Depending on how many pulses the fan sends per round - should be 0.5 or 1 - try...

  ########################################################
  # START THE FAN CONTROLLER SETUP

  - platform: template
    name: "${friendly_name} p term"
    id: p_term
    unit_of_measurement: "%"
    accuracy_decimals: 2

  - platform: template
    name: "${friendly_name} i term"
    id: i_term
    unit_of_measurement: "%"
    accuracy_decimals: 2

  - platform: template
    name: "${friendly_name} d term"
    id: d_term
    unit_of_measurement: "%"
    accuracy_decimals: 2

  - platform: template
    name: "${friendly_name} output value"
    unit_of_measurement: "%"
    id: o_term
    accuracy_decimals: 2

  - platform: template
    name: "${friendly_name} error value"
    id: e_term
    accuracy_decimals: 2

  - platform: template
    name: "${friendly_name} is in deadband"
    id: in_deadband_term
    accuracy_decimals: 0

  - platform: htu21d # compatible with sht21 and (even if not explicit) sht20)
    model: sht21 # OK for SHT20
    temperature:
      id: automate_fan_temperature
      name: "Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 2
      # If you don't smooth the temperature readings
      # the PID controller over reacts to small changes.
      filters:
         - exponential_moving_average:
             alpha: 0.1
             send_every: 1
    humidity:
      id: automate_fan_humidity
      name: "Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 2
      # If you don't smooth the temperature readings
      # the PID controller over reacts to small changes.
      filters:
         - exponential_moving_average:
             alpha: 0.1
             send_every: 1
    # the DHT11 can only be read every 1s. Use 1.3s to be safe.
    update_interval: 5s      # equivalente ai 5000 ms che usavi

  # derivated (but similar to previous setup)
  # 2) Punto di rugiada (Dew Point)
  - platform: template
    name: "Dew Point"
    id: automate_fan_dewpoint
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    update_interval: 5s
    lambda: |-
      const float T = id(automate_fan_temperature).state;
      const float RH = id(automate_fan_humidity).state;
      float alpha = log(RH / 100.0) + (17.27f * T) / (237.7f + T);
      return (237.7f * alpha) / (17.27f - alpha);

  # 3) Vapor Pressure Deficit (VPD)
  - platform: template
    name: "VPD"
    id: automate_fan_vpd
    unit_of_measurement: "kPa"
    accuracy_decimals: 2
    update_interval: 5s
    lambda: |-
      const float T = id(automate_fan_temperature).state;
      const float RH = id(automate_fan_humidity).state;
      float es = 0.61078f * exp(17.27f * T / (T + 237.3f));
      float ea = (RH / 100.0f) * es;
      return (es - ea);

  # Every time the fan speed is updated, this sensor will
  # also be updated for displaying on the frontend.
  # See proxy_output.
  - platform: template
    name: "Fan Speed (PWM Voltage)"
    unit_of_measurement: "%"
    id: fan_speed_pwm_voltage

output:
  # Wire this pin (13) into the PWM pin of your 12v fan
  # ledc is the name of the pwm output system on an esp32
  - platform: ledc
    id: automate_set_fan_speed
    pin: GPIO13 # 3rd pin fan1 & fan2
    # name: "Output Fan Speed" # invalid for output

    # 25KHz is standard PC fan frequency, minimises buzzing
    frequency: "25000 Hz"

    # my fans stop working below 13% powerful.
    # also they're  powerful and loud, cap their max speed to 80%
    # min_power: 13%
    # max_power: 80%
    # open door: 72% - closed door 85%
    min_power: 0%
    max_power: 100%
    # At 0, actually turn it off, otherwise the power keeps going.
    zero_means_zero: true

  # This proxy output takes its input
  # if the manual fan control is on, use the level from that
  # otherwise use the PID control value.
  # Then publish the result to the fan (ledc) and
  # also publish to the template output sensor
  - platform: template
    id: proxy_output
    type: float
    write_action:
      lambda: |-
        float write_val =
          (id(manual_fan_control).state) ?
            id(manual_fan_control).speed / 100.0 : state*1.0;
        id(automate_set_fan_speed).set_level(write_val);
        id(fan_speed_pwm_voltage).publish_state(write_val*100.0);

# If you turn this on, you can manually set the fan speed.
# The PID will be ignored. This is done via the proxy_output.
fan:
  - platform: speed
    id: manual_fan_control
    output: proxy_output
    name: "Manual Fan Speed"

# Expose a PID-controlled Thermostat
# Manual: https://esphome.io/components/climate/pid.html
climate:
  - platform: pid
    name: "${friendly_name} Thermostat"
    id: console_thermostat
    sensor: automate_fan_temperature

    # It is summer right now, so 30c is a decent target.
    default_target_temperature: 30°C
    #cool_output: automate_set_fan_speed
    cool_output: proxy_output
    #cool_output: automate_set_fan_speed

    # ON state change, publish the values to the x_term numbers defined
    # above, so that they can be viewed in HA
    on_state:
      - sensor.template.publish:
          id: p_term
          state: !lambda 'return -id(console_thermostat).get_proportional_term() * 100.0;'
      - sensor.template.publish:
          id: i_term
          state: !lambda 'return -id(console_thermostat).get_integral_term()* 100.0;'
      - sensor.template.publish:
          id: d_term
          state: !lambda 'return -id(console_thermostat).get_derivative_term()* 100.0;'
      - sensor.template.publish:
          id: o_term
          state: !lambda 'return -id(console_thermostat).get_output_value()* 100.0;'
      - sensor.template.publish:
          id: in_deadband_term
          state: !lambda 'return id(console_thermostat).in_deadband();'
      - sensor.template.publish:
          id: e_term
          state: !lambda 'return -id(console_thermostat).get_error_value();'

    # The extents of the HA Thermostat
    visual:
      min_temperature: 20 °C
      max_temperature: 50 °C

    # See the README for setting up these parameters.
    # These are over ridden by the number templates above.
    control_parameters:
      kp: 0.3
      ki: 0.0015
      kd: 0
      max_integral: 0.0
      output_averaging_samples: 1
      derivative_averaging_samples: 5

    # How to behave when close to the target temperature?
    deadband_parameters:
      threshold_high: 0.4°C
      threshold_low: -1.0°C
      kp_multiplier: 0.0
      ki_multiplier: 0.04
      kd_multiplier: 0.0
      deadband_output_averaging_samples: 15

switch:
  # Expose an ESP32 restart button to HA
  - platform: restart
    name: "${friendly_name} ESP32 Restart"
    id: automate_fan_restart

# Restart every day at 12:30am.
# I've had some memory issues lockup
# the device after a couple weeks
time:
  - platform: homeassistant
    on_time:
      # Every morning at 12:30am
      - seconds: 0
        minutes: 30
        hours: 0
        then:
          - switch.turn_on: automate_fan_restart


# I was able to find good KP,KI,KD values manually, per the instructions,
# but you can try pressing the autotune button from home assistant and copying the
# values it produces.
# See more at: https://esphome.io/components/climate/pid.html#climate-pid-autotune-action
button:
- platform: template
  name: "PID Climate Autotune"
  on_press:
    - climate.pid.autotune: console_thermostat

interval:
  - interval: 60s
    then:
      - lambda: |-
          // Log current IP address
          if (WiFi.isConnected()) {
            auto ip = WiFi.localIP().toString();
            ESP_LOGD("ip_logger", "Current IP: %s", ip.c_str());
          } else {
            ESP_LOGW("ip_logger", "WiFi not connected");
          }


